trade_config:
  amount: 1000

chart_config:
  instrument: USD_JPY
  granularity: M5
  wma_period: 20
  candle_count: 288

signal_config:
  wma_period: 20
  source_column: ha_low
  signal_buy_column: ha_bid_low
  signal_exit_column: ha_ask_high
  take_profit: 0.0
  stop_loss: 0.0