trade_config:
  amount: 1000

chart_config:
  instrument: USD_JPY
  granularity: M5
  wma_period: 20
  candle_count: 864

signal_config:
  wma_period: 20
  source_column: open
  signal_buy_column: ask_high
  signal_exit_column: ha_bid_high
  take_profit: 0.3
  stop_loss: 0.1