"""Configuration variables."""

BACKTEST_INTERVAL = 288 * 5

GRANULARITY = "M5"
WMA_PERIOD = 20
TAKE_PROFIT_MULTIPLIER = 2
TRAILING_STOP_LOSS_MULTIPLIER = 1
BACKTEST_COUNT = 288 * 3
REFRESH_RATE = 1
ENTRY_COLUMN = "ask_close"
EXIT_COLUMN = "bid_close"
SOURCE_COLUMN = ""
SIGNAL_BUY_COLUMN = ""
