"""Configuration variables."""

GRANULARITY = "M5"
WMA_PERIOD = 20
TAKE_PROFIT_MULTIPLIER = 3
TRAILING_STOP_LOSS_MULTIPLIER = 0
BACKTEST_COUNT = 288 * 3
ENTRY_COLUMN = "ask_close"
EXIT_COLUMN = "bid_close"
SOURCE_COLUMN = ""
SIGNAL_BUY_COLUMN = ""
